### ISSUE TITLE
cannot access ks-console

### ISSUE THREAD

**Issue by therealqxing** [kubesphere/ks-installer#1445]
> Kubernetes v1.17.9 deployed with kubespray
> Network plugin: Flannel (host-gw)
> KubeSphere version: v3.0.0

```
$ k get nodes -o wide
NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
node-195   Ready    <none>   3d    v1.17.9   172.20.53.195   <none>        CentOS Linux 7 (Core)   4.19.43-300.el7.x86_64   docker://19.3.12
node-213   Ready    master   3d    v1.17.9   172.20.53.213   <none>        CentOS Linux 7 (Core)   4.19.43-300.el7.x86_64   docker://19.3.12
node-219   Ready    master   3d    v1.17.9   172.20.53.219   <none>        CentOS Linux 7 (Core)   4.19.43-300.el7.x86_64   docker://19.3.12
```

```
$ k -n kubesphere-system get pods -o wide
NAME                                    READY   STATUS             RESTARTS   AGE    IP             NODE       NOMINATED NODE   READINESS GATES
ks-apiserver-fc5f9765-25m4r             1/1     Running            0          112m   10.224.0.133   node-195   <none>           <none>
ks-apiserver-fc5f9765-wgmdp             1/1     Running            8          112m   10.224.1.166   node-219   <none>           <none>
ks-console-67fc4bc8d8-f8p22             1/1     Running            0          18m    10.224.1.170   node-219   <none>           <none>
ks-console-67fc4bc8d8-q4l4j             1/1     Running            0          18m    10.224.0.134   node-195   <none>           <none>
ks-controller-manager-6c944d4b8-bwn7v   0/1     CrashLoopBackOff   22         112m   10.224.0.132   node-195   <none>           <none>
ks-controller-manager-6c944d4b8-w2zxs   1/1     Running            0          112m   10.224.2.153   node-213   <none>           <none>
ks-installer-5c6dc4c694-dppdq           1/1     Running            0          114m   10.224.1.160   node-219   <none>           <none>
openldap-0                              1/1     Running            0          40m    10.224.2.155   node-213   <none>           <none>
openldap-1                              1/1     Running            3          41m    10.224.1.169   node-219   <none>           <none>
redis-ha-haproxy-5f9dd6dcc5-4glfr       1/1     Running            0          114m   10.224.0.130   node-195   <none>           <none>
redis-ha-haproxy-5f9dd6dcc5-hkqm9       1/1     Running            0          114m   10.224.2.147   node-213   <none>           <none>
redis-ha-haproxy-5f9dd6dcc5-ts6j2       1/1     Running            0          114m   10.224.1.161   node-219   <none>           <none>
redis-ha-server-0                       2/2     Running            0          114m   10.224.2.150   node-213   <none>           <none>
redis-ha-server-1                       2/2     Running            0          114m   10.224.1.163   node-219   <none>           <none>
redis-ha-server-2                       2/2     Running            0          114m   10.224.0.131   node-195   <none>           <none>

$ k -n kubesphere-system logs ks-console-67fc4bc8d8-f8p22
 --> GET / 302 2ms 43b 2021/04/22T15:45:39.992
  <-- GET /login 2021/04/22T15:45:39.992
{ FetchError: request to http://ks-apiserver.kubesphere-system.svc/kapis/config.kubesphere.io/v1alpha2/configs/oauth failed, reason: getaddrinfo EAI_AGAIN ks-apiserver.kubesphere-system.svc:80
    at ClientRequest.<anonymous> (/opt/kubesphere/console/server/server.js:80604:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'request to http://ks-apiserver.kubesphere-system.svc/kapis/config.kubesphere.io/v1alpha2/configs/oauth failed, reason: getaddrinfo EAI_AGAIN ks-apiserver.kubesphere-system.svc:80',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
{ ReplyError: READONLY You can't write against a read only replica.
    at JavascriptRedisParser.returnError (/opt/kubesphere/console/server/server.js:62705:25)
    at JavascriptRedisParser.execute (/opt/kubesphere/console/server/server.js:63523:12)
    at Socket.<anonymous> (/opt/kubesphere/console/server/server.js:61970:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  name: 'ReplyError',
  message: 'READONLY You can\'t write against a read only replica.',
  command:
   { name: 'set',
     args:
      [ 'sid-CF2X24yrPSsRWw9xNIpwnctQzqiDq2pJ',
        '{"salt":"xQHBnHp9oTaV1Uu3"}',
        'EX',
        '7200000' ] } }
<-- GET / 2021/04/22T15:45:39.990
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
    at renderView (/opt/kubesphere/console/server/server.js:23231:46)
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
......
```

`ks-apiserver` doesn't have error logs.
```
$ k -n kubesphere-system logs ks-apiserver-fc5f9765-25m4r
W0422 14:29:52.644551       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0422 14:29:52.724427       1 apiserver.go:300] Start cache objects
I0422 14:29:53.501731       1 apiserver.go:502] Finished caching objects
I0422 14:29:53.501778       1 apiserver.go:232] Start listening on :9090
$
$ k -n kubesphere-system logs ks-apiserver-fc5f9765-wgmdp
W0422 14:46:22.836670       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0422 14:46:24.866603       1 apiserver.go:300] Start cache objects
I0422 14:46:25.605481       1 apiserver.go:502] Finished caching objects
I0422 14:46:25.605519       1 apiserver.go:232] Start listening on :9090
```

One of a `ks-controller-manager` crashs repeatedly, see error logs below.
```
$ k -n kubesphere-system logs ks-controller-manager-6c944d4b8-bwn7v
W0422 16:18:47.900992       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E0422 16:19:47.903235       1 server.go:81] failed to connect to ldap service, please check ldap status, error: factory is not able to fill the pool: LDAP Result Code 200 "Network Error": dial tcp 10.224.2.155:389: i/o timeout
```

and `openldap` error logs
```
$ k -n kubesphere-system logs openldap-1 -p
*** An error occurred. Aborting.
*** Init system aborted.
*** Not all processes have exited in time. Forcing them to exit.
```

**Comment by zryfish** [comment]
Please pay attention to this line 
```
  message: 'request to http://ks-apiserver.kubesphere-system.svc/kapis/config.kubesphere.io/v1alpha2/configs/oauth failed, reason: getaddrinfo EAI_AGAIN ks-apiserver.kubesphere-system.svc:80',
```

This kind of error log usually implies there is an error in DNS resolution, please check your cluster network, make sure all network components are running. And you may refer to https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ to help you debug.

**Comment by therealqxing** [comment]
I just try to resolve the ks-apiserver service name from ks-console, it seems it's normal.

```
$ k -n kubesphere-system exec ks-console-67fc4bc8d8-f8p22 -it -- nslookup ks-apiserver.kubesphere-system.svc
nslookup: can't resolve '(null)': Name does not resolve

Name:      ks-apiserver.kubesphere-system.svc
Address 1: 10.233.42.179
$
$ k -n kubesphere-system exec ks-console-67fc4bc8d8-q4l4j -it -- nslookup ks-apiserver.kubesphere-system.svc
nslookup: can't resolve '(null)': Name does not resolve

Name:      ks-apiserver.kubesphere-system.svc
Address 1: 10.233.42.179
$
$
$ k -n kubesphere-system describe svc ks-apiserver | grep Endpoint
Endpoints:         10.224.0.133:9090,10.224.1.166:9090
$
$
$ k -n kubesphere-system get pods -o wide | grep ks-apiserver | awk '{print $6}'
10.224.0.133
10.224.1.166
```
