### ISSUE TITLE
e2e was faild since the edgeruntime  installation failed on master build

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/ks-installer#1886]
```
**************************************************
Waiting for all tasks to be completed ...
task edgeruntime status is failed  (1/5)
task network status is successful  (2/5)
task openpitrix status is successful  (3/5)
task multicluster status is successful  (4/5)
task monitoring status is successful  (5/5)
**************************************************
Collecting installation results ...
Traceback (most recent call last):
  File "/hooks/kubesphere/installRunner.py", line 649, in <module>
    main()
  File "/hooks/kubesphere/installRunner.py", line 644, in main
    resultState = getResultInfo()
  File "/hooks/kubesphere/installRunner.py", line 238, in getResultInfo
    errorEventFile = os.path.join(resultInfoPath, jobList[-2])
IndexError: list index out of range
```
/kind bug 
/cc @zhu733756

**Comment by zhu733756** [comment]
Will fix tomorrow, pls set it to false not "fasle".  See https://github.com/kubesphere/ks-installer/blob/master/deploy/cluster-configuration.yaml#L150.
